local Languages = {
    ["English"] = {
        MessageBoxInThreadResponseTop = "Warning !",
        MessageBoxInThreadResponseInfo = "Are you sure you want to execute the script ? This will cause the current thread to cancel."
    },
    ["Français"] = {
        MessageBoxInThreadResponseTop = "Attention !",
        MessageBoxInThreadResponseInfo = "Êtes vous sure de vouloir executé le script ? Ceci annulera le fil actuel"
    }
}

return Languages
